// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHWVWbBLtGlO1OP3Cab8zttlrYGMim-o',
    appId: '1:492075751102:web:13c49eb1dfa88a7dc3b0ef',
    messagingSenderId: '492075751102',
    projectId: 'beststoreapp-1368c',
    authDomain: 'beststoreapp-1368c.firebaseapp.com',
    storageBucket: 'beststoreapp-1368c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjJLHYqS3xOo3tmncgq6UKYJI7K7nKVM',
    appId: '1:492075751102:android:a941e14918d59b2fc3b0ef',
    messagingSenderId: '492075751102',
    projectId: 'beststoreapp-1368c',
    storageBucket: 'beststoreapp-1368c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqyBR_ZWrxpTsC3AY5KEg5YX2J40fUA8',
    appId: '1:492075751102:ios:c1e244e856d32325c3b0ef',
    messagingSenderId: '492075751102',
    projectId: 'beststoreapp-1368c',
    storageBucket: 'beststoreapp-1368c.appspot.com',
    androidClientId: '492075751102-doghtnfvrc432dsfckqa57eegc195shh.apps.googleusercontent.com',
    iosClientId: '492075751102-s27j1j9qaqd70esjndnan855qigd9as3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
